#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin; export PATH

# ------------------------------------------------------------
# set file permissions
for f in \
    '/Library/Application Support/org.pqrs/NoEjectDelay' \
    '/Library/LaunchDaemons/org.pqrs.NoEjectDelay.load.plist' \
    ; do
    echo "set file permissions: $f"
    sh '/Library/Application Support/org.pqrs/NoEjectDelay/setpermissions.sh' "$f"
    chown -Rh root:wheel "$f"
done

# ------------------------------------------------------------
# load kext
sh "/Library/Application Support/org.pqrs/NoEjectDelay/startup.sh" start

# ------------------------------------------------------------
exit 0
